### ISSUE TITLE
Plugin config page does not work

### ISSUE THREAD

**Issue by tinwinaung** [mantisbt-plugins/scrum#13]
Could not update
<mantis-root>/plugin.php?page=Scrum/config_page

**Comment by tinwinaung** [comment]
Found config.php in config branch of the repo.

**Comment by dregad** [comment]
@tinwinaung The config page should not have made it into master just yet (I checked it in by mistake), as it's effectively still a work-in-progress. Long story short, use at your own risk... but do let me know if you encounter any issues.

**Comment by tinwinaung** [comment]
Thanks for info. I will submit ticket if I found any issues.
